2025-08-12 14:48:12,739 [INFO] [MainThread] [root/log.py:59]: YASB v1.7.9
2025-08-12 14:48:12,740 [INFO] [Thread-1 (_run_server)] [cli_server/cli_server.py:212]: CLI server started v1.1.2
2025-08-12 14:48:12,740 [INFO] [MainThread] [cli_server/cli_server.py:104]: Log pipe server started
2025-08-12 14:48:12,785 [INFO] [MainThread] [root/config.py:64]: Created default config file at C:\Users\Gengo\.config\yasb\config.yaml
2025-08-12 14:48:12,817 [INFO] [MainThread] [root/config.py:78]: Created default stylesheet at C:\Users\Gengo\.config\yasb\styles.css
2025-08-12 15:07:08,219 [DEBUG] [MainThread] [tzlocal/win32.py:55]: Looking up time zone info from registry
2025-08-12 15:07:14,034 [ERROR] [MainThread] [root/weather.py:57]: API key or location is missing. Please provide a valid API key and location.
2025-08-12 15:07:14,124 [DEBUG] [MainThread] [comtypes/__init__.py:149]: CoInitializeEx(None, 2)
2025-08-12 15:07:18,965 [INFO] [MainThread] [root/bar_manager.py:74]: Starting WindowsNotificationEventListener...
2025-08-12 15:07:18,966 [INFO] [MainThread] [root/bar_manager.py:74]: Starting SystemEventListener...
2025-08-12 15:07:18,967 [INFO] [MainThread] [root/bar_manager.py:74]: Starting KomorebiEventListener...
2025-08-12 15:07:18,967 [INFO] [MainThread] [root/watcher.py:54]: Created file watcher for path C:\Users\Gengo\.config\yasb
2025-08-12 15:07:18,972 [INFO] [Dummy-5] [root/event_listener.py:51]: Created named pipe yasb-2f8fa4d7-77a7-11f0-8bb2-b81ea4fe9ebe
2025-08-12 15:07:19,064 [DEBUG] [MainThread] [qasync._windows._EventPoller/_windows.py:213]: Starting (proactor: <_IocpProactor overlapped#=0 result#=0>)...
2025-08-12 15:07:19,069 [DEBUG] [Dummy-9] [qasync._windows._EventWorker/_windows.py:192]: Thread started
2025-08-12 15:07:19,239 [INFO] [Dummy-5] [root/event_listener.py:125]: Komorebi connected to named pipe: yasb-2f8fa4d7-77a7-11f0-8bb2-b81ea4fe9ebe
2025-08-12 15:07:19,348 [WARNING] [Thread-8 (check_for_update)] [root/update_check.py:50]: UpdateCheckService Failed to check for updates: Network error.
2025-08-12 15:18:54,321 [INFO] [MainThread] [root/log.py:59]: YASB v1.7.9
2025-08-12 15:18:54,324 [INFO] [Thread-1 (_run_server)] [cli_server/cli_server.py:212]: CLI server started v1.1.2
2025-08-12 15:18:54,324 [INFO] [MainThread] [cli_server/cli_server.py:104]: Log pipe server started
2025-08-12 15:18:54,325 [ERROR] [MainThread] [root/main.py:36]: Another instance of the YASB is already running.
2025-08-12 15:19:45,443 [INFO] [MainThread] [root/log.py:59]: YASB v1.7.9
2025-08-12 15:19:45,443 [INFO] [Thread-1 (_run_server)] [cli_server/cli_server.py:212]: CLI server started v1.1.2
2025-08-12 15:19:45,445 [INFO] [MainThread] [cli_server/cli_server.py:104]: Log pipe server started
2025-08-12 15:19:45,445 [ERROR] [MainThread] [root/main.py:36]: Another instance of the YASB is already running.
2025-08-12 15:20:27,931 [INFO] [MainThread] [root/log.py:59]: YASB v1.7.9
2025-08-12 15:20:27,933 [INFO] [Thread-1 (_run_server)] [cli_server/cli_server.py:212]: CLI server started v1.1.2
2025-08-12 15:20:27,933 [INFO] [MainThread] [cli_server/cli_server.py:104]: Log pipe server started
2025-08-12 15:20:27,934 [ERROR] [MainThread] [root/main.py:36]: Another instance of the YASB is already running.
2025-08-12 15:20:45,823 [INFO] [MainThread] [root/utilities.py:213]: YASB added to startup
2025-08-12 15:26:42,031 [INFO] [MainThread] [root/controller.py:15]: Reloading Application from tray...
2025-08-12 15:26:42,158 [INFO] [MainThread] [cli_server/cli_server.py:112]: Log pipe server stopped
2025-08-12 15:26:42,158 [DEBUG] [MainThread] [cli_server/cli_server.py:206]: CLI server stopped
2025-08-12 15:26:42,297 [DEBUG] [MainThread] [qasync._windows._EventPoller/_windows.py:218]: Stopping worker thread...
2025-08-12 15:26:42,312 [DEBUG] [Dummy-9] [qasync._windows._EventWorker/_windows.py:201]: Exiting thread
2025-08-12 15:26:42,321 [DEBUG] [MainThread] [qasync._windows._IocpProactor/_windows.py:75]: Closing
2025-08-12 15:26:42,440 [ERROR] [Dummy-5] [root/event_service.py:32]: Failed to emit signal <bound PYQT_SIGNAL k_signal_update of WorkspaceWidget object at 0x0000022AED251C70>. Removing link to KomorebiEvent.KomorebiUpdate.
2025-08-12 15:26:42,453 [ERROR] [Dummy-13] [root/event_service.py:32]: Failed to emit signal <bound PYQT_SIGNAL window_name_change of ActiveWindowWidget object at 0x0000022AED2D7A70>. Removing link to WinEvent.EventObjectNameChange.
2025-08-12 15:26:42,494 [ERROR] [Dummy-5] [root/event_service.py:32]: Failed to emit signal <bound PYQT_SIGNAL k_signal_update of ActiveLayoutWidget object at 0x0000022AED05BF70>. Removing link to KomorebiEvent.KomorebiUpdate.
2025-08-12 15:26:47,847 [INFO] [MainThread] [root/log.py:59]: YASB v1.7.9
2025-08-12 15:26:47,849 [INFO] [Thread-1 (_run_server)] [cli_server/cli_server.py:212]: CLI server started v1.1.2
2025-08-12 15:26:47,850 [INFO] [MainThread] [cli_server/cli_server.py:104]: Log pipe server started
2025-08-12 15:26:49,862 [DEBUG] [MainThread] [tzlocal/win32.py:55]: Looking up time zone info from registry
2025-08-12 15:26:54,049 [INFO] [MainThread] [root/log.py:59]: YASB v1.7.9
2025-08-12 15:26:54,050 [INFO] [Thread-1 (_run_server)] [cli_server/cli_server.py:212]: CLI server started v1.1.2
2025-08-12 15:26:54,050 [INFO] [MainThread] [cli_server/cli_server.py:104]: Log pipe server started
2025-08-12 15:26:54,050 [ERROR] [MainThread] [root/main.py:36]: Another instance of the YASB is already running.
2025-08-12 15:26:56,363 [ERROR] [MainThread] [root/weather.py:57]: API key or location is missing. Please provide a valid API key and location.
2025-08-12 15:26:56,453 [DEBUG] [MainThread] [comtypes/__init__.py:149]: CoInitializeEx(None, 2)
2025-08-12 15:27:00,982 [INFO] [MainThread] [root/bar_manager.py:74]: Starting KomorebiEventListener...
2025-08-12 15:27:00,983 [INFO] [MainThread] [root/bar_manager.py:74]: Starting WindowsNotificationEventListener...
2025-08-12 15:27:00,985 [INFO] [Dummy-3] [root/event_listener.py:51]: Created named pipe yasb-f018d125-77a9-11f0-94a5-b81ea4fe9ebe
2025-08-12 15:27:00,987 [INFO] [MainThread] [root/bar_manager.py:74]: Starting SystemEventListener...
2025-08-12 15:27:00,988 [INFO] [MainThread] [root/watcher.py:54]: Created file watcher for path C:\Users\Gengo\.config\yasb
2025-08-12 15:27:01,116 [DEBUG] [MainThread] [qasync._windows._EventPoller/_windows.py:213]: Starting (proactor: <_IocpProactor overlapped#=0 result#=0>)...
2025-08-12 15:27:01,124 [DEBUG] [Dummy-9] [qasync._windows._EventWorker/_windows.py:192]: Thread started
2025-08-12 15:27:01,260 [INFO] [Dummy-3] [root/event_listener.py:125]: Komorebi connected to named pipe: yasb-f018d125-77a9-11f0-94a5-b81ea4fe9ebe
2025-08-12 15:27:04,314 [INFO] [MainThread] [root/log.py:59]: YASB v1.7.9
2025-08-12 15:27:04,315 [INFO] [Thread-1 (_run_server)] [cli_server/cli_server.py:212]: CLI server started v1.1.2
2025-08-12 15:27:04,316 [INFO] [MainThread] [cli_server/cli_server.py:104]: Log pipe server started
2025-08-12 15:27:04,316 [ERROR] [MainThread] [root/main.py:36]: Another instance of the YASB is already running.
2025-08-12 19:06:24,058 [WARNING] [Dummy-3] [root/event_listener.py:82]: Pipe has been ended: (109, 'PeekNamedPipe', 'O pipe foi finalizado.')
2025-08-12 19:06:24,076 [INFO] [Dummy-3] [root/event_listener.py:92]: Attempting to reconnect to Komorebi...
2025-08-12 19:06:27,080 [INFO] [Dummy-3] [root/event_listener.py:51]: Created named pipe yasb-f018d125-77a9-11f0-94a5-b81ea4fe9ebe
2025-08-12 19:17:37,666 [INFO] [Dummy-3] [root/event_listener.py:125]: Komorebi connected to named pipe: yasb-f018d125-77a9-11f0-94a5-b81ea4fe9ebe
2025-08-12 19:42:47,539 [INFO] [MainThread] [root/controller.py:15]: Reloading Application because of config change.
2025-08-12 19:42:47,656 [INFO] [MainThread] [cli_server/cli_server.py:112]: Log pipe server stopped
2025-08-12 19:42:47,656 [DEBUG] [MainThread] [cli_server/cli_server.py:206]: CLI server stopped
2025-08-12 19:42:47,693 [INFO] [MainThread] [root/bar_manager.py:65]: Successfully loaded updated config and re-initialised all bars.
2025-08-12 19:42:47,699 [DEBUG] [MainThread] [qasync._windows._EventPoller/_windows.py:218]: Stopping worker thread...
2025-08-12 19:42:47,703 [DEBUG] [Dummy-9] [qasync._windows._EventWorker/_windows.py:201]: Exiting thread
2025-08-12 19:42:47,708 [DEBUG] [MainThread] [qasync._windows._IocpProactor/_windows.py:75]: Closing
2025-08-12 19:42:47,799 [ERROR] [Dummy-3] [root/event_service.py:32]: Failed to emit signal <bound PYQT_SIGNAL k_signal_update of WorkspaceWidget object at 0x000001E6171796D0>. Removing link to KomorebiEvent.KomorebiUpdate.
2025-08-12 19:42:48,250 [INFO] [MainThread] [root/log.py:59]: YASB v1.7.9
2025-08-12 19:42:48,250 [INFO] [Thread-1 (_run_server)] [cli_server/cli_server.py:212]: CLI server started v1.1.2
2025-08-12 19:42:48,251 [INFO] [MainThread] [cli_server/cli_server.py:104]: Log pipe server started
2025-08-12 19:42:48,819 [DEBUG] [MainThread] [tzlocal/win32.py:55]: Looking up time zone info from registry
2025-08-12 19:42:49,154 [ERROR] [MainThread] [root/weather.py:57]: API key or location is missing. Please provide a valid API key and location.
2025-08-12 19:42:49,159 [DEBUG] [MainThread] [comtypes/__init__.py:149]: CoInitializeEx(None, 2)
2025-08-12 19:42:51,493 [INFO] [MainThread] [root/bar_manager.py:74]: Starting KomorebiEventListener...
2025-08-12 19:42:51,494 [INFO] [MainThread] [root/bar_manager.py:74]: Starting SystemEventListener...
2025-08-12 19:42:51,494 [INFO] [MainThread] [root/bar_manager.py:74]: Starting WindowsNotificationEventListener...
2025-08-12 19:42:51,496 [INFO] [Dummy-3] [root/event_listener.py:51]: Created named pipe yasb-adb70375-77cd-11f0-92ee-b81ea4fe9ebe
2025-08-12 19:42:51,497 [INFO] [MainThread] [root/watcher.py:54]: Created file watcher for path C:\Users\Gengo\.config\yasb
2025-08-12 19:42:51,606 [DEBUG] [MainThread] [qasync._windows._EventPoller/_windows.py:213]: Starting (proactor: <_IocpProactor overlapped#=0 result#=0>)...
2025-08-12 19:42:51,609 [DEBUG] [Dummy-9] [qasync._windows._EventWorker/_windows.py:192]: Thread started
2025-08-12 19:42:51,691 [INFO] [Dummy-3] [root/event_listener.py:125]: Komorebi connected to named pipe: yasb-adb70375-77cd-11f0-92ee-b81ea4fe9ebe
2025-08-12 19:48:18,285 [INFO] [MainThread] [root/controller.py:15]: Reloading Application because of config change.
2025-08-12 19:48:18,389 [INFO] [MainThread] [cli_server/cli_server.py:112]: Log pipe server stopped
2025-08-12 19:48:18,390 [DEBUG] [MainThread] [cli_server/cli_server.py:206]: CLI server stopped
2025-08-12 19:48:18,426 [INFO] [MainThread] [root/bar_manager.py:65]: Successfully loaded updated config and re-initialised all bars.
2025-08-12 19:48:18,426 [DEBUG] [MainThread] [qasync._windows._EventPoller/_windows.py:218]: Stopping worker thread...
2025-08-12 19:48:18,450 [DEBUG] [Dummy-9] [qasync._windows._EventWorker/_windows.py:201]: Exiting thread
2025-08-12 19:48:18,452 [DEBUG] [MainThread] [qasync._windows._IocpProactor/_windows.py:75]: Closing
2025-08-12 19:48:18,493 [ERROR] [Dummy-3] [root/event_service.py:32]: Failed to emit signal <bound PYQT_SIGNAL k_signal_update of WorkspaceWidget object at 0x000001AE033996D0>. Removing link to KomorebiEvent.KomorebiUpdate.
2025-08-12 19:48:19,051 [INFO] [MainThread] [root/log.py:59]: YASB v1.7.9
2025-08-12 19:48:19,053 [INFO] [Thread-1 (_run_server)] [cli_server/cli_server.py:212]: CLI server started v1.1.2
2025-08-12 19:48:19,053 [INFO] [MainThread] [cli_server/cli_server.py:104]: Log pipe server started
2025-08-12 19:48:19,343 [DEBUG] [MainThread] [tzlocal/win32.py:55]: Looking up time zone info from registry
2025-08-12 19:48:19,511 [ERROR] [MainThread] [root/weather.py:57]: API key or location is missing. Please provide a valid API key and location.
2025-08-12 19:48:19,516 [DEBUG] [MainThread] [comtypes/__init__.py:149]: CoInitializeEx(None, 2)
2025-08-12 19:48:20,862 [INFO] [MainThread] [root/bar_manager.py:74]: Starting KomorebiEventListener...
2025-08-12 19:48:20,862 [INFO] [MainThread] [root/bar_manager.py:74]: Starting SystemEventListener...
2025-08-12 19:48:20,863 [INFO] [MainThread] [root/bar_manager.py:74]: Starting WindowsNotificationEventListener...
2025-08-12 19:48:20,865 [INFO] [Dummy-3] [root/event_listener.py:51]: Created named pipe yasb-7208a637-77ce-11f0-b120-b81ea4fe9ebe
2025-08-12 19:48:20,865 [INFO] [MainThread] [root/watcher.py:54]: Created file watcher for path C:\Users\Gengo\.config\yasb
2025-08-12 19:48:20,925 [DEBUG] [MainThread] [qasync._windows._EventPoller/_windows.py:213]: Starting (proactor: <_IocpProactor overlapped#=0 result#=0>)...
2025-08-12 19:48:20,926 [DEBUG] [Dummy-9] [qasync._windows._EventWorker/_windows.py:192]: Thread started
2025-08-12 19:48:20,987 [INFO] [Dummy-3] [root/event_listener.py:125]: Komorebi connected to named pipe: yasb-7208a637-77ce-11f0-b120-b81ea4fe9ebe
2025-08-12 19:50:06,393 [INFO] [MainThread] [root/controller.py:15]: Reloading Application because of config change.
2025-08-12 19:50:06,506 [INFO] [MainThread] [cli_server/cli_server.py:112]: Log pipe server stopped
2025-08-12 19:50:06,506 [DEBUG] [MainThread] [cli_server/cli_server.py:206]: CLI server stopped
2025-08-12 19:50:06,520 [INFO] [MainThread] [root/bar_manager.py:65]: Successfully loaded updated config and re-initialised all bars.
2025-08-12 19:50:06,520 [DEBUG] [MainThread] [qasync._windows._EventPoller/_windows.py:218]: Stopping worker thread...
2025-08-12 19:50:06,522 [DEBUG] [Dummy-9] [qasync._windows._EventWorker/_windows.py:201]: Exiting thread
2025-08-12 19:50:06,524 [DEBUG] [MainThread] [qasync._windows._IocpProactor/_windows.py:75]: Closing
2025-08-12 19:50:06,597 [ERROR] [Dummy-3] [root/event_service.py:32]: Failed to emit signal <bound PYQT_SIGNAL k_signal_update of WorkspaceWidget object at 0x000001F12A7396D0>. Removing link to KomorebiEvent.KomorebiUpdate.
2025-08-12 19:50:06,597 [ERROR] [Dummy-3] [root/event_service.py:32]: Failed to emit signal <bound PYQT_SIGNAL k_signal_update of ActiveLayoutWidget object at 0x000001F12A773ED0>. Removing link to KomorebiEvent.KomorebiUpdate.
2025-08-12 19:50:07,089 [INFO] [MainThread] [root/log.py:59]: YASB v1.7.9
2025-08-12 19:50:07,090 [INFO] [Thread-1 (_run_server)] [cli_server/cli_server.py:212]: CLI server started v1.1.2
2025-08-12 19:50:07,091 [INFO] [MainThread] [cli_server/cli_server.py:104]: Log pipe server started
2025-08-12 19:50:07,397 [DEBUG] [MainThread] [tzlocal/win32.py:55]: Looking up time zone info from registry
2025-08-12 19:50:07,533 [ERROR] [MainThread] [root/weather.py:57]: API key or location is missing. Please provide a valid API key and location.
2025-08-12 19:50:07,537 [DEBUG] [MainThread] [comtypes/__init__.py:149]: CoInitializeEx(None, 2)
2025-08-12 19:50:08,697 [INFO] [MainThread] [root/bar_manager.py:74]: Starting KomorebiEventListener...
2025-08-12 19:50:08,698 [INFO] [MainThread] [root/bar_manager.py:74]: Starting SystemEventListener...
2025-08-12 19:50:08,698 [INFO] [MainThread] [root/bar_manager.py:74]: Starting WindowsNotificationEventListener...
2025-08-12 19:50:08,699 [INFO] [Dummy-3] [root/event_listener.py:51]: Created named pipe yasb-b24f17b6-77ce-11f0-971c-b81ea4fe9ebe
2025-08-12 19:50:08,700 [INFO] [MainThread] [root/watcher.py:54]: Created file watcher for path C:\Users\Gengo\.config\yasb
2025-08-12 19:50:08,751 [DEBUG] [MainThread] [qasync._windows._EventPoller/_windows.py:213]: Starting (proactor: <_IocpProactor overlapped#=0 result#=0>)...
2025-08-12 19:50:08,752 [DEBUG] [Dummy-9] [qasync._windows._EventWorker/_windows.py:192]: Thread started
2025-08-12 19:50:08,819 [INFO] [Dummy-3] [root/event_listener.py:125]: Komorebi connected to named pipe: yasb-b24f17b6-77ce-11f0-971c-b81ea4fe9ebe
2025-08-12 19:51:55,653 [ERROR] [MainThread] [root/bar_manager.py:54]: Error loading config: while scanning a double-quoted scalar
  in "C:\Users\Gengo\.config\yasb\config.yaml", line 249, column 42
found unknown escape character 'M'
  in "C:\Users\Gengo\.config\yasb\config.yaml", line 249, column 66
2025-08-12 19:52:25,324 [INFO] [MainThread] [root/controller.py:15]: Reloading Application because of config change.
2025-08-12 19:52:25,439 [INFO] [MainThread] [cli_server/cli_server.py:112]: Log pipe server stopped
2025-08-12 19:52:25,439 [DEBUG] [MainThread] [cli_server/cli_server.py:206]: CLI server stopped
2025-08-12 19:52:25,453 [INFO] [MainThread] [root/bar_manager.py:65]: Successfully loaded updated config and re-initialised all bars.
2025-08-12 19:52:25,453 [DEBUG] [MainThread] [qasync._windows._EventPoller/_windows.py:218]: Stopping worker thread...
2025-08-12 19:52:25,454 [DEBUG] [Dummy-9] [qasync._windows._EventWorker/_windows.py:201]: Exiting thread
2025-08-12 19:52:25,456 [DEBUG] [MainThread] [qasync._windows._IocpProactor/_windows.py:75]: Closing
2025-08-12 19:52:25,529 [ERROR] [Dummy-3] [root/event_service.py:32]: Failed to emit signal <bound PYQT_SIGNAL k_signal_update of WorkspaceWidget object at 0x00000206C33596D0>. Removing link to KomorebiEvent.KomorebiUpdate.
2025-08-12 19:52:25,529 [ERROR] [Dummy-3] [root/event_service.py:32]: Failed to emit signal <bound PYQT_SIGNAL k_signal_update of ActiveLayoutWidget object at 0x00000206C3393ED0>. Removing link to KomorebiEvent.KomorebiUpdate.
2025-08-12 19:52:26,044 [INFO] [MainThread] [root/log.py:59]: YASB v1.7.9
2025-08-12 19:52:26,045 [INFO] [Thread-1 (_run_server)] [cli_server/cli_server.py:212]: CLI server started v1.1.2
2025-08-12 19:52:26,046 [INFO] [MainThread] [cli_server/cli_server.py:104]: Log pipe server started
2025-08-12 19:52:26,366 [DEBUG] [MainThread] [tzlocal/win32.py:55]: Looking up time zone info from registry
2025-08-12 19:52:26,564 [ERROR] [MainThread] [root/weather.py:57]: API key or location is missing. Please provide a valid API key and location.
2025-08-12 19:52:26,567 [DEBUG] [MainThread] [comtypes/__init__.py:149]: CoInitializeEx(None, 2)
2025-08-12 19:52:27,709 [INFO] [MainThread] [root/bar_manager.py:74]: Starting KomorebiEventListener...
2025-08-12 19:52:27,710 [INFO] [MainThread] [root/bar_manager.py:74]: Starting SystemEventListener...
2025-08-12 19:52:27,710 [INFO] [MainThread] [root/bar_manager.py:74]: Starting WindowsNotificationEventListener...
2025-08-12 19:52:27,711 [INFO] [MainThread] [root/watcher.py:54]: Created file watcher for path C:\Users\Gengo\.config\yasb
2025-08-12 19:52:27,712 [INFO] [Dummy-5] [root/event_listener.py:51]: Created named pipe yasb-052a8d88-77cf-11f0-ace0-b81ea4fe9ebe
2025-08-12 19:52:27,765 [DEBUG] [MainThread] [qasync._windows._EventPoller/_windows.py:213]: Starting (proactor: <_IocpProactor overlapped#=0 result#=0>)...
2025-08-12 19:52:27,767 [DEBUG] [Dummy-9] [qasync._windows._EventWorker/_windows.py:192]: Thread started
2025-08-12 19:52:27,854 [INFO] [Dummy-5] [root/event_listener.py:125]: Komorebi connected to named pipe: yasb-052a8d88-77cf-11f0-ace0-b81ea4fe9ebe
2025-08-12 20:00:26,614 [INFO] [MainThread] [root/controller.py:15]: Reloading Application because of config change.
2025-08-12 20:00:26,724 [INFO] [MainThread] [cli_server/cli_server.py:112]: Log pipe server stopped
2025-08-12 20:00:26,724 [DEBUG] [MainThread] [cli_server/cli_server.py:206]: CLI server stopped
2025-08-12 20:00:26,753 [INFO] [MainThread] [root/bar_manager.py:65]: Successfully loaded updated config and re-initialised all bars.
2025-08-12 20:00:26,753 [DEBUG] [MainThread] [qasync._windows._EventPoller/_windows.py:218]: Stopping worker thread...
2025-08-12 20:00:26,771 [DEBUG] [Dummy-9] [qasync._windows._EventWorker/_windows.py:201]: Exiting thread
2025-08-12 20:00:26,772 [DEBUG] [MainThread] [qasync._windows._IocpProactor/_windows.py:75]: Closing
2025-08-12 20:00:26,866 [ERROR] [Dummy-5] [root/event_service.py:32]: Failed to emit signal <bound PYQT_SIGNAL k_signal_update of WorkspaceWidget object at 0x000001F148B396D0>. Removing link to KomorebiEvent.KomorebiUpdate.
2025-08-12 20:00:26,917 [ERROR] [Dummy-5] [root/event_service.py:32]: Failed to emit signal <bound PYQT_SIGNAL k_signal_update of ActiveLayoutWidget object at 0x000001F148B73ED0>. Removing link to KomorebiEvent.KomorebiUpdate.
2025-08-12 20:00:27,381 [INFO] [MainThread] [root/log.py:59]: YASB v1.7.9
2025-08-12 20:00:27,383 [INFO] [Thread-1 (_run_server)] [cli_server/cli_server.py:212]: CLI server started v1.1.2
2025-08-12 20:00:27,383 [INFO] [MainThread] [cli_server/cli_server.py:104]: Log pipe server started
2025-08-12 20:00:27,802 [DEBUG] [MainThread] [tzlocal/win32.py:55]: Looking up time zone info from registry
2025-08-12 20:00:27,973 [DEBUG] [MainThread] [comtypes/__init__.py:149]: CoInitializeEx(None, 2)
2025-08-12 20:00:30,143 [INFO] [MainThread] [root/bar_manager.py:74]: Starting SystemEventListener...
2025-08-12 20:00:30,144 [INFO] [MainThread] [root/bar_manager.py:74]: Starting WindowsNotificationEventListener...
2025-08-12 20:00:30,146 [INFO] [MainThread] [root/bar_manager.py:74]: Starting KomorebiEventListener...
2025-08-12 20:00:30,147 [INFO] [MainThread] [root/watcher.py:54]: Created file watcher for path C:\Users\Gengo\.config\yasb
2025-08-12 20:00:30,152 [INFO] [Dummy-5] [root/event_listener.py:51]: Created named pipe yasb-24b89786-77d0-11f0-af53-b81ea4fe9ebe
2025-08-12 20:00:30,231 [DEBUG] [MainThread] [qasync._windows._EventPoller/_windows.py:213]: Starting (proactor: <_IocpProactor overlapped#=0 result#=0>)...
2025-08-12 20:00:30,234 [DEBUG] [Dummy-9] [qasync._windows._EventWorker/_windows.py:192]: Thread started
2025-08-12 20:00:30,335 [INFO] [Dummy-5] [root/event_listener.py:125]: Komorebi connected to named pipe: yasb-24b89786-77d0-11f0-af53-b81ea4fe9ebe
2025-08-12 20:00:30,764 [INFO] [MainThread] [root/api.py:57]: Fetching new weather data at 2025-08-12 20:00:30.764774
2025-08-12 20:02:09,411 [INFO] [MainThread] [root/controller.py:15]: Reloading Application because of config change.
2025-08-12 20:02:09,526 [INFO] [MainThread] [cli_server/cli_server.py:112]: Log pipe server stopped
2025-08-12 20:02:09,526 [DEBUG] [MainThread] [cli_server/cli_server.py:206]: CLI server stopped
2025-08-12 20:02:09,551 [INFO] [MainThread] [root/bar_manager.py:65]: Successfully loaded updated config and re-initialised all bars.
2025-08-12 20:02:09,552 [DEBUG] [MainThread] [qasync._windows._EventPoller/_windows.py:218]: Stopping worker thread...
2025-08-12 20:02:09,572 [DEBUG] [Dummy-9] [qasync._windows._EventWorker/_windows.py:201]: Exiting thread
2025-08-12 20:02:09,575 [DEBUG] [MainThread] [qasync._windows._IocpProactor/_windows.py:75]: Closing
2025-08-12 20:02:09,665 [ERROR] [Dummy-5] [root/event_service.py:32]: Failed to emit signal <bound PYQT_SIGNAL k_signal_update of WorkspaceWidget object at 0x000001D7049E96D0>. Removing link to KomorebiEvent.KomorebiUpdate.
2025-08-12 20:02:09,666 [ERROR] [Dummy-5] [root/event_service.py:32]: Failed to emit signal <bound PYQT_SIGNAL k_signal_update of ActiveLayoutWidget object at 0x000001D704A23ED0>. Removing link to KomorebiEvent.KomorebiUpdate.
2025-08-12 20:02:10,135 [INFO] [MainThread] [root/log.py:59]: YASB v1.7.9
2025-08-12 20:02:10,136 [INFO] [Thread-1 (_run_server)] [cli_server/cli_server.py:212]: CLI server started v1.1.2
2025-08-12 20:02:10,136 [INFO] [MainThread] [cli_server/cli_server.py:104]: Log pipe server started
2025-08-12 20:02:10,456 [DEBUG] [MainThread] [tzlocal/win32.py:55]: Looking up time zone info from registry
2025-08-12 20:02:10,655 [DEBUG] [MainThread] [comtypes/__init__.py:149]: CoInitializeEx(None, 2)
2025-08-12 20:02:12,001 [INFO] [MainThread] [root/bar_manager.py:74]: Starting KomorebiEventListener...
2025-08-12 20:02:12,001 [INFO] [MainThread] [root/bar_manager.py:74]: Starting WindowsNotificationEventListener...
2025-08-12 20:02:12,003 [INFO] [Dummy-3] [root/event_listener.py:51]: Created named pipe yasb-616e7654-77d0-11f0-918c-b81ea4fe9ebe
2025-08-12 20:02:12,003 [INFO] [MainThread] [root/bar_manager.py:74]: Starting SystemEventListener...
2025-08-12 20:02:12,003 [INFO] [MainThread] [root/watcher.py:54]: Created file watcher for path C:\Users\Gengo\.config\yasb
2025-08-12 20:02:12,058 [DEBUG] [MainThread] [qasync._windows._EventPoller/_windows.py:213]: Starting (proactor: <_IocpProactor overlapped#=0 result#=0>)...
2025-08-12 20:02:12,059 [DEBUG] [Dummy-9] [qasync._windows._EventWorker/_windows.py:192]: Thread started
2025-08-12 20:02:12,129 [INFO] [Dummy-3] [root/event_listener.py:125]: Komorebi connected to named pipe: yasb-616e7654-77d0-11f0-918c-b81ea4fe9ebe
2025-08-12 20:02:12,531 [INFO] [MainThread] [root/api.py:57]: Fetching new weather data at 2025-08-12 20:02:12.531990
2025-08-12 20:02:33,209 [INFO] [MainThread] [root/controller.py:15]: Reloading Application because of config change.
2025-08-12 20:02:33,313 [INFO] [MainThread] [cli_server/cli_server.py:112]: Log pipe server stopped
2025-08-12 20:02:33,313 [DEBUG] [MainThread] [cli_server/cli_server.py:206]: CLI server stopped
2025-08-12 20:02:33,330 [INFO] [MainThread] [root/bar_manager.py:65]: Successfully loaded updated config and re-initialised all bars.
2025-08-12 20:02:33,331 [DEBUG] [MainThread] [qasync._windows._EventPoller/_windows.py:218]: Stopping worker thread...
2025-08-12 20:02:33,345 [DEBUG] [Dummy-9] [qasync._windows._EventWorker/_windows.py:201]: Exiting thread
2025-08-12 20:02:33,349 [DEBUG] [MainThread] [qasync._windows._IocpProactor/_windows.py:75]: Closing
2025-08-12 20:02:33,415 [ERROR] [Dummy-3] [root/event_service.py:32]: Failed to emit signal <bound PYQT_SIGNAL k_signal_update of WorkspaceWidget object at 0x000002894ABE96D0>. Removing link to KomorebiEvent.KomorebiUpdate.
2025-08-12 20:02:33,423 [ERROR] [Dummy-11] [root/event_service.py:32]: Failed to emit signal <bound PYQT_SIGNAL window_name_change of ActiveWindowWidget object at 0x000002894AC87930>. Removing link to WinEvent.EventObjectNameChange.
2025-08-12 20:02:33,894 [INFO] [MainThread] [root/log.py:59]: YASB v1.7.9
2025-08-12 20:02:33,895 [INFO] [Thread-1 (_run_server)] [cli_server/cli_server.py:212]: CLI server started v1.1.2
2025-08-12 20:02:33,895 [INFO] [MainThread] [cli_server/cli_server.py:104]: Log pipe server started
2025-08-12 20:02:34,198 [DEBUG] [MainThread] [tzlocal/win32.py:55]: Looking up time zone info from registry
2025-08-12 20:02:34,398 [DEBUG] [MainThread] [comtypes/__init__.py:149]: CoInitializeEx(None, 2)
2025-08-12 20:02:35,544 [INFO] [MainThread] [root/bar_manager.py:74]: Starting KomorebiEventListener...
2025-08-12 20:02:35,545 [INFO] [MainThread] [root/bar_manager.py:74]: Starting WindowsNotificationEventListener...
2025-08-12 20:02:35,546 [INFO] [Dummy-3] [root/event_listener.py:51]: Created named pipe yasb-6f76c6ec-77d0-11f0-8a1e-b81ea4fe9ebe
2025-08-12 20:02:35,548 [INFO] [MainThread] [root/bar_manager.py:74]: Starting SystemEventListener...
2025-08-12 20:02:35,548 [INFO] [MainThread] [root/watcher.py:54]: Created file watcher for path C:\Users\Gengo\.config\yasb
2025-08-12 20:02:35,607 [DEBUG] [MainThread] [qasync._windows._EventPoller/_windows.py:213]: Starting (proactor: <_IocpProactor overlapped#=0 result#=0>)...
2025-08-12 20:02:35,608 [DEBUG] [Dummy-9] [qasync._windows._EventWorker/_windows.py:192]: Thread started
2025-08-12 20:02:35,671 [INFO] [Dummy-3] [root/event_listener.py:125]: Komorebi connected to named pipe: yasb-6f76c6ec-77d0-11f0-8a1e-b81ea4fe9ebe
2025-08-12 20:02:35,989 [INFO] [MainThread] [root/api.py:57]: Fetching new weather data at 2025-08-12 20:02:35.989346
2025-08-12 20:03:04,387 [INFO] [MainThread] [root/controller.py:15]: Reloading Application because of config change.
2025-08-12 20:03:04,489 [INFO] [MainThread] [cli_server/cli_server.py:112]: Log pipe server stopped
2025-08-12 20:03:04,490 [DEBUG] [MainThread] [cli_server/cli_server.py:206]: CLI server stopped
2025-08-12 20:03:04,510 [INFO] [MainThread] [root/bar_manager.py:65]: Successfully loaded updated config and re-initialised all bars.
2025-08-12 20:03:04,510 [DEBUG] [MainThread] [qasync._windows._EventPoller/_windows.py:218]: Stopping worker thread...
2025-08-12 20:03:04,520 [DEBUG] [Dummy-9] [qasync._windows._EventWorker/_windows.py:201]: Exiting thread
2025-08-12 20:03:04,523 [DEBUG] [MainThread] [qasync._windows._IocpProactor/_windows.py:75]: Closing
2025-08-12 20:03:04,592 [ERROR] [Dummy-3] [root/event_service.py:32]: Failed to emit signal <bound PYQT_SIGNAL k_signal_update of WorkspaceWidget object at 0x000002257B3896D0>. Removing link to KomorebiEvent.KomorebiUpdate.
2025-08-12 20:03:05,085 [INFO] [MainThread] [root/log.py:59]: YASB v1.7.9
2025-08-12 20:03:05,086 [INFO] [Thread-1 (_run_server)] [cli_server/cli_server.py:212]: CLI server started v1.1.2
2025-08-12 20:03:05,087 [INFO] [MainThread] [cli_server/cli_server.py:104]: Log pipe server started
2025-08-12 20:03:05,392 [DEBUG] [MainThread] [tzlocal/win32.py:55]: Looking up time zone info from registry
2025-08-12 20:03:05,586 [DEBUG] [MainThread] [comtypes/__init__.py:149]: CoInitializeEx(None, 2)
2025-08-12 20:03:07,132 [INFO] [MainThread] [root/bar_manager.py:74]: Starting KomorebiEventListener...
2025-08-12 20:03:07,133 [INFO] [MainThread] [root/bar_manager.py:74]: Starting WindowsNotificationEventListener...
2025-08-12 20:03:07,135 [INFO] [MainThread] [root/bar_manager.py:74]: Starting SystemEventListener...
2025-08-12 20:03:07,135 [INFO] [Dummy-3] [root/event_listener.py:51]: Created named pipe yasb-824aef6c-77d0-11f0-a5f2-b81ea4fe9ebe
2025-08-12 20:03:07,136 [INFO] [MainThread] [root/watcher.py:54]: Created file watcher for path C:\Users\Gengo\.config\yasb
2025-08-12 20:03:07,194 [DEBUG] [MainThread] [qasync._windows._EventPoller/_windows.py:213]: Starting (proactor: <_IocpProactor overlapped#=0 result#=0>)...
2025-08-12 20:03:07,196 [DEBUG] [Dummy-9] [qasync._windows._EventWorker/_windows.py:192]: Thread started
2025-08-12 20:03:07,272 [INFO] [Dummy-3] [root/event_listener.py:125]: Komorebi connected to named pipe: yasb-824aef6c-77d0-11f0-a5f2-b81ea4fe9ebe
2025-08-12 20:03:07,633 [INFO] [MainThread] [root/api.py:57]: Fetching new weather data at 2025-08-12 20:03:07.632528
2025-08-12 20:04:59,743 [INFO] [MainThread] [root/controller.py:15]: Reloading Application because of config change.
2025-08-12 20:04:59,858 [INFO] [MainThread] [cli_server/cli_server.py:112]: Log pipe server stopped
2025-08-12 20:04:59,858 [DEBUG] [MainThread] [cli_server/cli_server.py:206]: CLI server stopped
2025-08-12 20:04:59,872 [INFO] [MainThread] [root/bar_manager.py:65]: Successfully loaded updated config and re-initialised all bars.
2025-08-12 20:04:59,872 [DEBUG] [MainThread] [qasync._windows._EventPoller/_windows.py:218]: Stopping worker thread...
2025-08-12 20:04:59,873 [DEBUG] [Dummy-9] [qasync._windows._EventWorker/_windows.py:201]: Exiting thread
2025-08-12 20:04:59,875 [DEBUG] [MainThread] [qasync._windows._IocpProactor/_windows.py:75]: Closing
2025-08-12 20:04:59,950 [ERROR] [Dummy-3] [root/event_service.py:32]: Failed to emit signal <bound PYQT_SIGNAL k_signal_update of WorkspaceWidget object at 0x000001AD50BD96D0>. Removing link to KomorebiEvent.KomorebiUpdate.
2025-08-12 20:05:00,540 [INFO] [MainThread] [root/log.py:59]: YASB v1.7.9
2025-08-12 20:05:00,541 [INFO] [Thread-1 (_run_server)] [cli_server/cli_server.py:212]: CLI server started v1.1.2
2025-08-12 20:05:00,542 [INFO] [MainThread] [cli_server/cli_server.py:104]: Log pipe server started
2025-08-12 20:05:00,835 [DEBUG] [MainThread] [tzlocal/win32.py:55]: Looking up time zone info from registry
2025-08-12 20:05:01,056 [DEBUG] [MainThread] [comtypes/__init__.py:149]: CoInitializeEx(None, 2)
2025-08-12 20:05:02,255 [INFO] [MainThread] [root/bar_manager.py:74]: Starting SystemEventListener...
2025-08-12 20:05:02,256 [INFO] [MainThread] [root/bar_manager.py:74]: Starting WindowsNotificationEventListener...
2025-08-12 20:05:02,257 [INFO] [MainThread] [root/bar_manager.py:74]: Starting KomorebiEventListener...
2025-08-12 20:05:02,258 [INFO] [MainThread] [root/watcher.py:54]: Created file watcher for path C:\Users\Gengo\.config\yasb
2025-08-12 20:05:02,259 [INFO] [Dummy-5] [root/event_listener.py:51]: Created named pipe yasb-c6e95b74-77d0-11f0-a3c4-b81ea4fe9ebe
2025-08-12 20:05:02,313 [DEBUG] [MainThread] [qasync._windows._EventPoller/_windows.py:213]: Starting (proactor: <_IocpProactor overlapped#=0 result#=0>)...
2025-08-12 20:05:02,314 [DEBUG] [Dummy-9] [qasync._windows._EventWorker/_windows.py:192]: Thread started
2025-08-12 20:05:02,372 [INFO] [Dummy-5] [root/event_listener.py:125]: Komorebi connected to named pipe: yasb-c6e95b74-77d0-11f0-a3c4-b81ea4fe9ebe
2025-08-12 20:05:02,455 [INFO] [MainThread] [root/api.py:57]: Fetching new weather data at 2025-08-12 20:05:02.454922
2025-08-12 20:05:39,455 [INFO] [MainThread] [root/controller.py:15]: Reloading Application because of config change.
2025-08-12 20:05:39,561 [INFO] [MainThread] [cli_server/cli_server.py:112]: Log pipe server stopped
2025-08-12 20:05:39,561 [DEBUG] [MainThread] [cli_server/cli_server.py:206]: CLI server stopped
2025-08-12 20:05:39,579 [INFO] [MainThread] [root/bar_manager.py:65]: Successfully loaded updated config and re-initialised all bars.
2025-08-12 20:05:39,579 [DEBUG] [MainThread] [qasync._windows._EventPoller/_windows.py:218]: Stopping worker thread...
2025-08-12 20:05:39,593 [DEBUG] [Dummy-9] [qasync._windows._EventWorker/_windows.py:201]: Exiting thread
2025-08-12 20:05:39,595 [DEBUG] [MainThread] [qasync._windows._IocpProactor/_windows.py:75]: Closing
2025-08-12 20:05:40,280 [INFO] [MainThread] [root/log.py:59]: YASB v1.7.9
2025-08-12 20:05:40,281 [INFO] [Thread-1 (_run_server)] [cli_server/cli_server.py:212]: CLI server started v1.1.2
2025-08-12 20:05:40,282 [INFO] [MainThread] [cli_server/cli_server.py:104]: Log pipe server started
2025-08-12 20:05:40,572 [DEBUG] [MainThread] [tzlocal/win32.py:55]: Looking up time zone info from registry
2025-08-12 20:05:40,758 [DEBUG] [MainThread] [comtypes/__init__.py:149]: CoInitializeEx(None, 2)
2025-08-12 20:05:41,880 [INFO] [MainThread] [root/bar_manager.py:74]: Starting KomorebiEventListener...
2025-08-12 20:05:41,880 [INFO] [MainThread] [root/bar_manager.py:74]: Starting WindowsNotificationEventListener...
2025-08-12 20:05:41,881 [INFO] [Dummy-3] [root/event_listener.py:51]: Created named pipe yasb-de877d18-77d0-11f0-814e-b81ea4fe9ebe
2025-08-12 20:05:41,883 [INFO] [MainThread] [root/bar_manager.py:74]: Starting SystemEventListener...
2025-08-12 20:05:41,883 [INFO] [MainThread] [root/watcher.py:54]: Created file watcher for path C:\Users\Gengo\.config\yasb
2025-08-12 20:05:41,936 [DEBUG] [MainThread] [qasync._windows._EventPoller/_windows.py:213]: Starting (proactor: <_IocpProactor overlapped#=0 result#=0>)...
2025-08-12 20:05:41,937 [DEBUG] [Dummy-9] [qasync._windows._EventWorker/_windows.py:192]: Thread started
2025-08-12 20:05:41,997 [INFO] [Dummy-3] [root/event_listener.py:125]: Komorebi connected to named pipe: yasb-de877d18-77d0-11f0-814e-b81ea4fe9ebe
2025-08-12 20:05:42,355 [INFO] [MainThread] [root/api.py:57]: Fetching new weather data at 2025-08-12 20:05:42.355658
2025-08-12 20:06:45,751 [INFO] [MainThread] [root/controller.py:15]: Reloading Application from tray...
2025-08-12 20:06:45,855 [INFO] [MainThread] [cli_server/cli_server.py:112]: Log pipe server stopped
2025-08-12 20:06:45,857 [DEBUG] [MainThread] [cli_server/cli_server.py:206]: CLI server stopped
2025-08-12 20:06:45,902 [DEBUG] [MainThread] [qasync._windows._EventPoller/_windows.py:218]: Stopping worker thread...
2025-08-12 20:06:45,917 [DEBUG] [Dummy-9] [qasync._windows._EventWorker/_windows.py:201]: Exiting thread
2025-08-12 20:06:45,920 [DEBUG] [MainThread] [qasync._windows._IocpProactor/_windows.py:75]: Closing
2025-08-12 20:06:46,031 [ERROR] [Dummy-11] [root/event_service.py:32]: Failed to emit signal <bound PYQT_SIGNAL window_name_change of ActiveWindowWidget object at 0x0000023B01077930>. Removing link to WinEvent.EventObjectStateChange.
2025-08-12 20:06:46,090 [ERROR] [Dummy-3] [root/event_service.py:32]: Failed to emit signal <bound PYQT_SIGNAL k_signal_update of WorkspaceWidget object at 0x0000023B00FD96D0>. Removing link to KomorebiEvent.KomorebiUpdate.
2025-08-12 20:06:46,090 [ERROR] [Dummy-3] [root/event_service.py:32]: Failed to emit signal <bound PYQT_SIGNAL k_signal_update of ActiveLayoutWidget object at 0x0000023B01013ED0>. Removing link to KomorebiEvent.KomorebiUpdate.
2025-08-12 20:06:46,429 [INFO] [MainThread] [root/log.py:59]: YASB v1.7.9
2025-08-12 20:06:46,430 [INFO] [Thread-1 (_run_server)] [cli_server/cli_server.py:212]: CLI server started v1.1.2
2025-08-12 20:06:46,431 [INFO] [MainThread] [cli_server/cli_server.py:104]: Log pipe server started
2025-08-12 20:06:46,775 [DEBUG] [MainThread] [tzlocal/win32.py:55]: Looking up time zone info from registry
2025-08-12 20:06:46,958 [DEBUG] [MainThread] [comtypes/__init__.py:149]: CoInitializeEx(None, 2)
2025-08-12 20:06:48,225 [INFO] [MainThread] [root/bar_manager.py:74]: Starting KomorebiEventListener...
2025-08-12 20:06:48,226 [INFO] [MainThread] [root/bar_manager.py:74]: Starting SystemEventListener...
2025-08-12 20:06:48,226 [INFO] [MainThread] [root/bar_manager.py:74]: Starting WindowsNotificationEventListener...
2025-08-12 20:06:48,227 [INFO] [Dummy-3] [root/event_listener.py:51]: Created named pipe yasb-0612ccdb-77d1-11f0-b666-b81ea4fe9ebe
2025-08-12 20:06:48,227 [INFO] [MainThread] [root/watcher.py:54]: Created file watcher for path C:\Users\Gengo\.config\yasb
2025-08-12 20:06:48,284 [DEBUG] [MainThread] [qasync._windows._EventPoller/_windows.py:213]: Starting (proactor: <_IocpProactor overlapped#=0 result#=0>)...
2025-08-12 20:06:48,285 [DEBUG] [Dummy-9] [qasync._windows._EventWorker/_windows.py:192]: Thread started
2025-08-12 20:06:48,351 [INFO] [Dummy-3] [root/event_listener.py:125]: Komorebi connected to named pipe: yasb-0612ccdb-77d1-11f0-b666-b81ea4fe9ebe
2025-08-12 20:06:48,406 [INFO] [MainThread] [root/api.py:57]: Fetching new weather data at 2025-08-12 20:06:48.406675
2025-08-12 20:16:47,272 [INFO] [MainThread] [root/api.py:57]: Fetching new weather data at 2025-08-12 20:16:47.272262
2025-08-12 20:26:47,310 [INFO] [MainThread] [root/api.py:57]: Fetching new weather data at 2025-08-12 20:26:47.310700
2025-08-12 20:36:47,291 [INFO] [MainThread] [root/api.py:57]: Fetching new weather data at 2025-08-12 20:36:47.291642
2025-08-12 20:46:47,287 [INFO] [MainThread] [root/api.py:57]: Fetching new weather data at 2025-08-12 20:46:47.287195
2025-08-12 20:50:34,803 [ERROR] [MainThread] [root/config.py:115]: The config file 'C:\Users\Gengo\.config\yasb\config.yaml' contains validation errors. Please fix:
widgets:
- wallpapers:
  - null value not allowed

2025-08-12 20:51:30,071 [ERROR] [MainThread] [root/config.py:115]: The config file 'C:\Users\Gengo\.config\yasb\config.yaml' contains validation errors. Please fix:
widgets:
- wallpapers:
  - null value not allowed

2025-08-12 20:52:31,622 [ERROR] [MainThread] [root/bar_manager.py:54]: Error loading config: while scanning a double-quoted scalar
  in "C:\Users\Gengo\.config\yasb\config.yaml", line 266, column 17
found unknown escape character 'G'
  in "C:\Users\Gengo\.config\yasb\config.yaml", line 266, column 28
2025-08-12 20:53:48,690 [ERROR] [MainThread] [root/bar_manager.py:54]: Error loading config: while scanning a double-quoted scalar
  in "C:\Users\Gengo\.config\yasb\config.yaml", line 267, column 17
found unknown escape character 'G'
  in "C:\Users\Gengo\.config\yasb\config.yaml", line 267, column 28
2025-08-12 20:53:59,903 [INFO] [MainThread] [root/controller.py:15]: Reloading Application from tray...
2025-08-12 20:54:00,018 [INFO] [MainThread] [cli_server/cli_server.py:112]: Log pipe server stopped
2025-08-12 20:54:00,018 [DEBUG] [MainThread] [cli_server/cli_server.py:206]: CLI server stopped
2025-08-12 20:54:00,094 [DEBUG] [MainThread] [qasync._windows._EventPoller/_windows.py:218]: Stopping worker thread...
2025-08-12 20:54:00,112 [DEBUG] [Dummy-9] [qasync._windows._EventWorker/_windows.py:201]: Exiting thread
2025-08-12 20:54:00,114 [DEBUG] [MainThread] [qasync._windows._IocpProactor/_windows.py:75]: Closing
2025-08-12 20:54:00,160 [ERROR] [Dummy-3] [root/event_service.py:32]: Failed to emit signal <bound PYQT_SIGNAL k_signal_update of WorkspaceWidget object at 0x00000160101F96D0>. Removing link to KomorebiEvent.KomorebiUpdate.
2025-08-12 20:54:00,211 [ERROR] [Dummy-3] [root/event_service.py:32]: Failed to emit signal <bound PYQT_SIGNAL k_signal_update of ActiveLayoutWidget object at 0x0000016010233ED0>. Removing link to KomorebiEvent.KomorebiUpdate.
2025-08-12 20:54:00,680 [INFO] [MainThread] [root/log.py:59]: YASB v1.7.9
2025-08-12 20:54:00,681 [INFO] [Thread-1 (_run_server)] [cli_server/cli_server.py:212]: CLI server started v1.1.2
2025-08-12 20:54:00,682 [INFO] [MainThread] [cli_server/cli_server.py:104]: Log pipe server started
2025-08-12 20:54:00,753 [ERROR] [MainThread] [root/main.py:111]: Exception during application startup
Traceback (most recent call last):
  File "main.py", line 109, in <module>
  File "main.py", line 51, in main
  File "D:\a\yasb\yasb\src\core\config.py", line 155, in get_config_and_stylesheet
  File "D:\a\yasb\yasb\src\core\config.py", line 109, in get_config
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\__init__.py", line 125, in safe_load
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\__init__.py", line 81, in load
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\constructor.py", line 49, in get_single_data
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\composer.py", line 36, in get_single_node
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\composer.py", line 55, in compose_document
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\composer.py", line 84, in compose_node
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\composer.py", line 133, in compose_mapping_node
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\composer.py", line 84, in compose_node
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\composer.py", line 133, in compose_mapping_node
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\composer.py", line 84, in compose_node
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\composer.py", line 133, in compose_mapping_node
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\composer.py", line 64, in compose_node
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\parser.py", line 98, in check_event
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\parser.py", line 449, in parse_block_mapping_value
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\scanner.py", line 116, in check_token
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\scanner.py", line 251, in fetch_more_tokens
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\scanner.py", line 655, in fetch_double
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\scanner.py", line 666, in fetch_flow_scalar
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\scanner.py", line 1149, in scan_flow_scalar
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\scanner.py", line 1223, in scan_flow_scalar_non_spaces
yaml.scanner.ScannerError: while scanning a double-quoted scalar
  in "C:\Users\Gengo\.config\yasb\config.yaml", line 267, column 17
found unknown escape character 'G'
  in "C:\Users\Gengo\.config\yasb\config.yaml", line 267, column 28
2025-08-12 20:54:15,317 [INFO] [MainThread] [root/log.py:59]: YASB v1.7.9
2025-08-12 20:54:15,317 [INFO] [Thread-1 (_run_server)] [cli_server/cli_server.py:212]: CLI server started v1.1.2
2025-08-12 20:54:15,318 [INFO] [MainThread] [cli_server/cli_server.py:104]: Log pipe server started
2025-08-12 20:54:15,368 [ERROR] [MainThread] [root/main.py:111]: Exception during application startup
Traceback (most recent call last):
  File "main.py", line 109, in <module>
  File "main.py", line 51, in main
  File "D:\a\yasb\yasb\src\core\config.py", line 155, in get_config_and_stylesheet
  File "D:\a\yasb\yasb\src\core\config.py", line 109, in get_config
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\__init__.py", line 125, in safe_load
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\__init__.py", line 81, in load
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\constructor.py", line 49, in get_single_data
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\composer.py", line 36, in get_single_node
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\composer.py", line 55, in compose_document
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\composer.py", line 84, in compose_node
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\composer.py", line 133, in compose_mapping_node
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\composer.py", line 84, in compose_node
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\composer.py", line 133, in compose_mapping_node
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\composer.py", line 84, in compose_node
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\composer.py", line 133, in compose_mapping_node
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\composer.py", line 64, in compose_node
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\parser.py", line 98, in check_event
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\parser.py", line 449, in parse_block_mapping_value
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\scanner.py", line 116, in check_token
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\scanner.py", line 251, in fetch_more_tokens
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\scanner.py", line 655, in fetch_double
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\scanner.py", line 666, in fetch_flow_scalar
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\scanner.py", line 1149, in scan_flow_scalar
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\scanner.py", line 1223, in scan_flow_scalar_non_spaces
yaml.scanner.ScannerError: while scanning a double-quoted scalar
  in "C:\Users\Gengo\.config\yasb\config.yaml", line 267, column 17
found unknown escape character 'G'
  in "C:\Users\Gengo\.config\yasb\config.yaml", line 267, column 28
2025-08-12 20:54:25,668 [INFO] [MainThread] [root/log.py:59]: YASB v1.7.9
2025-08-12 20:54:25,669 [INFO] [Thread-1 (_run_server)] [cli_server/cli_server.py:212]: CLI server started v1.1.2
2025-08-12 20:54:25,669 [INFO] [MainThread] [cli_server/cli_server.py:104]: Log pipe server started
2025-08-12 20:54:25,722 [ERROR] [MainThread] [root/main.py:111]: Exception during application startup
Traceback (most recent call last):
  File "main.py", line 109, in <module>
  File "main.py", line 51, in main
  File "D:\a\yasb\yasb\src\core\config.py", line 155, in get_config_and_stylesheet
  File "D:\a\yasb\yasb\src\core\config.py", line 109, in get_config
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\__init__.py", line 125, in safe_load
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\__init__.py", line 81, in load
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\constructor.py", line 49, in get_single_data
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\composer.py", line 36, in get_single_node
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\composer.py", line 55, in compose_document
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\composer.py", line 84, in compose_node
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\composer.py", line 133, in compose_mapping_node
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\composer.py", line 84, in compose_node
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\composer.py", line 133, in compose_mapping_node
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\composer.py", line 84, in compose_node
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\composer.py", line 133, in compose_mapping_node
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\composer.py", line 64, in compose_node
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\parser.py", line 98, in check_event
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\parser.py", line 449, in parse_block_mapping_value
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\scanner.py", line 116, in check_token
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\scanner.py", line 251, in fetch_more_tokens
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\scanner.py", line 655, in fetch_double
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\scanner.py", line 666, in fetch_flow_scalar
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\scanner.py", line 1149, in scan_flow_scalar
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\scanner.py", line 1223, in scan_flow_scalar_non_spaces
yaml.scanner.ScannerError: while scanning a double-quoted scalar
  in "C:\Users\Gengo\.config\yasb\config.yaml", line 267, column 17
found unknown escape character 'G'
  in "C:\Users\Gengo\.config\yasb\config.yaml", line 267, column 28
2025-08-12 20:54:41,732 [INFO] [MainThread] [root/log.py:59]: YASB v1.7.9
2025-08-12 20:54:41,733 [INFO] [Thread-1 (_run_server)] [cli_server/cli_server.py:212]: CLI server started v1.1.2
2025-08-12 20:54:41,734 [INFO] [MainThread] [cli_server/cli_server.py:104]: Log pipe server started
2025-08-12 20:54:41,821 [ERROR] [MainThread] [root/main.py:111]: Exception during application startup
Traceback (most recent call last):
  File "main.py", line 109, in <module>
  File "main.py", line 51, in main
  File "D:\a\yasb\yasb\src\core\config.py", line 155, in get_config_and_stylesheet
  File "D:\a\yasb\yasb\src\core\config.py", line 109, in get_config
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\__init__.py", line 125, in safe_load
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\__init__.py", line 81, in load
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\constructor.py", line 49, in get_single_data
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\composer.py", line 36, in get_single_node
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\composer.py", line 55, in compose_document
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\composer.py", line 84, in compose_node
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\composer.py", line 133, in compose_mapping_node
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\composer.py", line 84, in compose_node
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\composer.py", line 133, in compose_mapping_node
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\composer.py", line 84, in compose_node
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\composer.py", line 133, in compose_mapping_node
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\composer.py", line 64, in compose_node
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\parser.py", line 98, in check_event
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\parser.py", line 449, in parse_block_mapping_value
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\scanner.py", line 116, in check_token
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\scanner.py", line 251, in fetch_more_tokens
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\scanner.py", line 655, in fetch_double
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\scanner.py", line 666, in fetch_flow_scalar
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\scanner.py", line 1149, in scan_flow_scalar
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\scanner.py", line 1223, in scan_flow_scalar_non_spaces
yaml.scanner.ScannerError: while scanning a double-quoted scalar
  in "C:\Users\Gengo\.config\yasb\config.yaml", line 267, column 17
found unknown escape character 'G'
  in "C:\Users\Gengo\.config\yasb\config.yaml", line 267, column 28
2025-08-12 20:55:10,373 [INFO] [MainThread] [root/log.py:59]: YASB v1.7.9
2025-08-12 20:55:10,374 [INFO] [Thread-1 (_run_server)] [cli_server/cli_server.py:212]: CLI server started v1.1.2
2025-08-12 20:55:10,374 [INFO] [MainThread] [cli_server/cli_server.py:104]: Log pipe server started
2025-08-12 20:55:10,470 [ERROR] [MainThread] [root/config.py:115]: The config file 'C:\Users\Gengo\.config\yasb\config.yaml' contains validation errors. Please fix:
widgets:
- wallpapers:
  - null value not allowed

2025-08-12 20:55:10,472 [ERROR] [MainThread] [root/config.py:168]: User config file could not be loaded. Exiting Application.
2025-08-12 20:56:59,776 [INFO] [MainThread] [root/log.py:59]: YASB v1.7.9
2025-08-12 20:56:59,778 [INFO] [Thread-1 (_run_server)] [cli_server/cli_server.py:212]: CLI server started v1.1.2
2025-08-12 20:56:59,778 [INFO] [MainThread] [cli_server/cli_server.py:104]: Log pipe server started
2025-08-12 20:56:59,833 [ERROR] [MainThread] [root/main.py:111]: Exception during application startup
Traceback (most recent call last):
  File "main.py", line 109, in <module>
  File "main.py", line 51, in main
  File "D:\a\yasb\yasb\src\core\config.py", line 155, in get_config_and_stylesheet
  File "D:\a\yasb\yasb\src\core\config.py", line 109, in get_config
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\__init__.py", line 125, in safe_load
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\__init__.py", line 81, in load
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\constructor.py", line 49, in get_single_data
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\composer.py", line 36, in get_single_node
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\composer.py", line 55, in compose_document
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\composer.py", line 84, in compose_node
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\composer.py", line 133, in compose_mapping_node
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\composer.py", line 84, in compose_node
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\composer.py", line 133, in compose_mapping_node
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\composer.py", line 84, in compose_node
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\composer.py", line 133, in compose_mapping_node
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\composer.py", line 64, in compose_node
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\parser.py", line 98, in check_event
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\parser.py", line 449, in parse_block_mapping_value
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\scanner.py", line 116, in check_token
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\scanner.py", line 251, in fetch_more_tokens
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\scanner.py", line 655, in fetch_double
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\scanner.py", line 666, in fetch_flow_scalar
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\scanner.py", line 1149, in scan_flow_scalar
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\scanner.py", line 1213, in scan_flow_scalar_non_spaces
yaml.scanner.ScannerError: while scanning a double-quoted scalar
  in "C:\Users\Gengo\.config\yasb\config.yaml", line 267, column 17
expected escape sequence of 8 hexadecimal numbers, but found 's'
  in "C:\Users\Gengo\.config\yasb\config.yaml", line 267, column 22
2025-08-12 20:57:09,299 [INFO] [MainThread] [root/log.py:59]: YASB v1.7.9
2025-08-12 20:57:09,299 [INFO] [Thread-1 (_run_server)] [cli_server/cli_server.py:212]: CLI server started v1.1.2
2025-08-12 20:57:09,300 [INFO] [MainThread] [cli_server/cli_server.py:104]: Log pipe server started
2025-08-12 20:57:09,374 [ERROR] [MainThread] [root/main.py:111]: Exception during application startup
Traceback (most recent call last):
  File "main.py", line 109, in <module>
  File "main.py", line 51, in main
  File "D:\a\yasb\yasb\src\core\config.py", line 155, in get_config_and_stylesheet
  File "D:\a\yasb\yasb\src\core\config.py", line 109, in get_config
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\__init__.py", line 125, in safe_load
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\__init__.py", line 81, in load
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\constructor.py", line 49, in get_single_data
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\composer.py", line 36, in get_single_node
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\composer.py", line 55, in compose_document
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\composer.py", line 84, in compose_node
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\composer.py", line 133, in compose_mapping_node
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\composer.py", line 84, in compose_node
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\composer.py", line 133, in compose_mapping_node
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\composer.py", line 84, in compose_node
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\composer.py", line 133, in compose_mapping_node
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\composer.py", line 64, in compose_node
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\parser.py", line 98, in check_event
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\parser.py", line 449, in parse_block_mapping_value
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\scanner.py", line 116, in check_token
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\scanner.py", line 251, in fetch_more_tokens
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\scanner.py", line 655, in fetch_double
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\scanner.py", line 666, in fetch_flow_scalar
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\scanner.py", line 1149, in scan_flow_scalar
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\scanner.py", line 1213, in scan_flow_scalar_non_spaces
yaml.scanner.ScannerError: while scanning a double-quoted scalar
  in "C:\Users\Gengo\.config\yasb\config.yaml", line 267, column 17
expected escape sequence of 8 hexadecimal numbers, but found 's'
  in "C:\Users\Gengo\.config\yasb\config.yaml", line 267, column 22
2025-08-12 20:57:16,748 [INFO] [MainThread] [root/log.py:59]: YASB v1.7.9
2025-08-12 20:57:16,749 [INFO] [Thread-1 (_run_server)] [cli_server/cli_server.py:212]: CLI server started v1.1.2
2025-08-12 20:57:16,749 [INFO] [MainThread] [cli_server/cli_server.py:104]: Log pipe server started
2025-08-12 20:57:16,781 [ERROR] [MainThread] [root/main.py:111]: Exception during application startup
Traceback (most recent call last):
  File "main.py", line 109, in <module>
  File "main.py", line 51, in main
  File "D:\a\yasb\yasb\src\core\config.py", line 155, in get_config_and_stylesheet
  File "D:\a\yasb\yasb\src\core\config.py", line 109, in get_config
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\__init__.py", line 125, in safe_load
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\__init__.py", line 81, in load
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\constructor.py", line 49, in get_single_data
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\composer.py", line 36, in get_single_node
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\composer.py", line 55, in compose_document
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\composer.py", line 84, in compose_node
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\composer.py", line 133, in compose_mapping_node
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\composer.py", line 84, in compose_node
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\composer.py", line 133, in compose_mapping_node
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\composer.py", line 84, in compose_node
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\composer.py", line 133, in compose_mapping_node
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\composer.py", line 64, in compose_node
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\parser.py", line 98, in check_event
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\parser.py", line 449, in parse_block_mapping_value
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\scanner.py", line 116, in check_token
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\scanner.py", line 251, in fetch_more_tokens
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\scanner.py", line 655, in fetch_double
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\scanner.py", line 666, in fetch_flow_scalar
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\scanner.py", line 1149, in scan_flow_scalar
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\scanner.py", line 1213, in scan_flow_scalar_non_spaces
yaml.scanner.ScannerError: while scanning a double-quoted scalar
  in "C:\Users\Gengo\.config\yasb\config.yaml", line 267, column 17
expected escape sequence of 8 hexadecimal numbers, but found 's'
  in "C:\Users\Gengo\.config\yasb\config.yaml", line 267, column 22
2025-08-12 20:57:20,135 [INFO] [MainThread] [root/log.py:59]: YASB v1.7.9
2025-08-12 20:57:20,136 [INFO] [Thread-1 (_run_server)] [cli_server/cli_server.py:212]: CLI server started v1.1.2
2025-08-12 20:57:20,136 [INFO] [MainThread] [cli_server/cli_server.py:104]: Log pipe server started
2025-08-12 20:57:20,167 [ERROR] [MainThread] [root/main.py:111]: Exception during application startup
Traceback (most recent call last):
  File "main.py", line 109, in <module>
  File "main.py", line 51, in main
  File "D:\a\yasb\yasb\src\core\config.py", line 155, in get_config_and_stylesheet
  File "D:\a\yasb\yasb\src\core\config.py", line 109, in get_config
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\__init__.py", line 125, in safe_load
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\__init__.py", line 81, in load
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\constructor.py", line 49, in get_single_data
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\composer.py", line 36, in get_single_node
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\composer.py", line 55, in compose_document
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\composer.py", line 84, in compose_node
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\composer.py", line 133, in compose_mapping_node
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\composer.py", line 84, in compose_node
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\composer.py", line 133, in compose_mapping_node
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\composer.py", line 84, in compose_node
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\composer.py", line 133, in compose_mapping_node
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\composer.py", line 64, in compose_node
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\parser.py", line 98, in check_event
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\parser.py", line 449, in parse_block_mapping_value
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\scanner.py", line 116, in check_token
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\scanner.py", line 251, in fetch_more_tokens
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\scanner.py", line 655, in fetch_double
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\scanner.py", line 666, in fetch_flow_scalar
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\scanner.py", line 1149, in scan_flow_scalar
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\scanner.py", line 1213, in scan_flow_scalar_non_spaces
yaml.scanner.ScannerError: while scanning a double-quoted scalar
  in "C:\Users\Gengo\.config\yasb\config.yaml", line 267, column 17
expected escape sequence of 8 hexadecimal numbers, but found 's'
  in "C:\Users\Gengo\.config\yasb\config.yaml", line 267, column 22
2025-08-12 20:57:26,662 [INFO] [MainThread] [root/log.py:59]: YASB v1.7.9
2025-08-12 20:57:26,663 [INFO] [Thread-1 (_run_server)] [cli_server/cli_server.py:212]: CLI server started v1.1.2
2025-08-12 20:57:26,663 [INFO] [MainThread] [cli_server/cli_server.py:104]: Log pipe server started
2025-08-12 20:57:26,692 [ERROR] [MainThread] [root/main.py:111]: Exception during application startup
Traceback (most recent call last):
  File "main.py", line 109, in <module>
  File "main.py", line 51, in main
  File "D:\a\yasb\yasb\src\core\config.py", line 155, in get_config_and_stylesheet
  File "D:\a\yasb\yasb\src\core\config.py", line 109, in get_config
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\__init__.py", line 125, in safe_load
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\__init__.py", line 81, in load
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\constructor.py", line 49, in get_single_data
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\composer.py", line 36, in get_single_node
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\composer.py", line 55, in compose_document
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\composer.py", line 84, in compose_node
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\composer.py", line 133, in compose_mapping_node
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\composer.py", line 84, in compose_node
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\composer.py", line 133, in compose_mapping_node
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\composer.py", line 84, in compose_node
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\composer.py", line 133, in compose_mapping_node
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\composer.py", line 64, in compose_node
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\parser.py", line 98, in check_event
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\parser.py", line 449, in parse_block_mapping_value
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\scanner.py", line 116, in check_token
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\scanner.py", line 251, in fetch_more_tokens
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\scanner.py", line 655, in fetch_double
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\scanner.py", line 666, in fetch_flow_scalar
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\scanner.py", line 1149, in scan_flow_scalar
  File "D:\a\yasb\yasb\venv\Lib\site-packages\yaml\scanner.py", line 1213, in scan_flow_scalar_non_spaces
yaml.scanner.ScannerError: while scanning a double-quoted scalar
  in "C:\Users\Gengo\.config\yasb\config.yaml", line 267, column 17
expected escape sequence of 8 hexadecimal numbers, but found 's'
  in "C:\Users\Gengo\.config\yasb\config.yaml", line 267, column 22
2025-08-12 20:59:38,238 [INFO] [MainThread] [root/log.py:59]: YASB v1.7.9
2025-08-12 20:59:38,239 [INFO] [Thread-1 (_run_server)] [cli_server/cli_server.py:212]: CLI server started v1.1.2
2025-08-12 20:59:38,240 [INFO] [MainThread] [cli_server/cli_server.py:104]: Log pipe server started
2025-08-12 20:59:38,327 [ERROR] [MainThread] [root/config.py:115]: The config file 'C:\Users\Gengo\.config\yasb\config.yaml' contains validation errors. Please fix:
widgets:
- wallpapers:
  - null value not allowed

2025-08-12 20:59:38,339 [ERROR] [MainThread] [root/config.py:168]: User config file could not be loaded. Exiting Application.
2025-08-12 20:59:45,687 [INFO] [MainThread] [root/log.py:59]: YASB v1.7.9
2025-08-12 20:59:45,688 [INFO] [Thread-1 (_run_server)] [cli_server/cli_server.py:212]: CLI server started v1.1.2
2025-08-12 20:59:45,689 [INFO] [MainThread] [cli_server/cli_server.py:104]: Log pipe server started
2025-08-12 20:59:45,744 [ERROR] [MainThread] [root/config.py:115]: The config file 'C:\Users\Gengo\.config\yasb\config.yaml' contains validation errors. Please fix:
widgets:
- wallpapers:
  - null value not allowed

2025-08-12 20:59:45,746 [ERROR] [MainThread] [root/config.py:168]: User config file could not be loaded. Exiting Application.
2025-08-12 21:03:31,563 [INFO] [MainThread] [root/log.py:59]: YASB v1.7.9
2025-08-12 21:03:31,564 [INFO] [Thread-1 (_run_server)] [cli_server/cli_server.py:212]: CLI server started v1.1.2
2025-08-12 21:03:31,564 [INFO] [MainThread] [cli_server/cli_server.py:104]: Log pipe server started
2025-08-12 21:03:31,632 [ERROR] [MainThread] [root/config.py:115]: The config file 'C:\Users\Gengo\.config\yasb\config.yaml' contains validation errors. Please fix:
widgets:
- wallpapers:
  - null value not allowed

2025-08-12 21:03:31,634 [ERROR] [MainThread] [root/config.py:168]: User config file could not be loaded. Exiting Application.
2025-08-12 21:04:11,327 [INFO] [MainThread] [root/log.py:59]: YASB v1.7.9
2025-08-12 21:04:11,328 [INFO] [Thread-1 (_run_server)] [cli_server/cli_server.py:212]: CLI server started v1.1.2
2025-08-12 21:04:11,329 [INFO] [MainThread] [cli_server/cli_server.py:104]: Log pipe server started
2025-08-12 21:04:11,394 [ERROR] [MainThread] [root/config.py:115]: The config file 'C:\Users\Gengo\.config\yasb\config.yaml' contains validation errors. Please fix:
widgets:
- wallpapers:
  - null value not allowed

2025-08-12 21:04:11,396 [ERROR] [MainThread] [root/config.py:168]: User config file could not be loaded. Exiting Application.
2025-08-12 21:07:29,528 [INFO] [MainThread] [root/log.py:59]: YASB v1.7.9
2025-08-12 21:07:29,529 [INFO] [Thread-1 (_run_server)] [cli_server/cli_server.py:212]: CLI server started v1.1.2
2025-08-12 21:07:29,529 [INFO] [MainThread] [cli_server/cli_server.py:104]: Log pipe server started
2025-08-12 21:07:29,609 [ERROR] [MainThread] [root/config.py:115]: The config file 'C:\Users\Gengo\.config\yasb\config.yaml' contains validation errors. Please fix:
widgets:
- wallpapers:
  - null value not allowed

2025-08-12 21:07:29,627 [ERROR] [MainThread] [root/config.py:168]: User config file could not be loaded. Exiting Application.
